import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Button, Card, CardContent, CardTitle, Input, CircleBadge } from '@boby/ui';
export function ProfilePage() {
    return (_jsxs("div", { className: "max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8 animate-fade-in", children: [_jsxs("div", { className: "mb-8", children: [_jsx("h1", { className: "text-2xl sm:text-3xl font-bold text-text-primary", children: "Profile" }), _jsx("p", { className: "text-text-muted mt-1", children: "Manage your account and credentials" })] }), _jsxs("div", { className: "grid lg:grid-cols-3 gap-6", children: [_jsx(Card, { variant: "elevated", padding: "lg", className: "lg:col-span-1", children: _jsxs(CardContent, { className: "text-center", children: [_jsx("div", { className: "w-24 h-24 rounded-full bg-primary mx-auto mb-4 flex items-center justify-center", children: _jsx("span", { className: "text-2xl font-bold text-text-primary", children: "AG" }) }), _jsx("h2", { className: "text-xl font-bold text-text-primary", children: "Agent Name" }), _jsx("p", { className: "text-text-muted mb-4", children: "agent@example.com" }), _jsx("div", { className: "flex justify-center gap-2 mb-4", children: _jsx(CircleBadge, { level: "inner" }) }), _jsxs("div", { className: "grid grid-cols-2 gap-4 pt-4 border-t border-grey-200", children: [_jsxs("div", { children: [_jsx("p", { className: "text-2xl font-bold text-text-primary", children: "94" }), _jsx("p", { className: "text-sm text-text-muted", children: "Trust Score" })] }), _jsxs("div", { children: [_jsx("p", { className: "text-2xl font-bold text-text-primary", children: "127" }), _jsx("p", { className: "text-sm text-text-muted", children: "Jobs Done" })] })] })] }) }), _jsxs(Card, { variant: "default", padding: "lg", className: "lg:col-span-2", children: [_jsx(CardTitle, { className: "mb-6", children: "Personal Information" }), _jsxs("div", { className: "grid sm:grid-cols-2 gap-4", children: [_jsx(Input, { label: "First Name", defaultValue: "Agent" }), _jsx(Input, { label: "Last Name", defaultValue: "Name" }), _jsx(Input, { label: "Email", type: "email", defaultValue: "agent@example.com" }), _jsx(Input, { label: "Phone", type: "tel", defaultValue: "+61 400 000 000" }), _jsx(Input, { label: "Security Licence #", defaultValue: "QLD-12345678", className: "sm:col-span-2" })] }), _jsx("div", { className: "flex justify-end mt-6", children: _jsx(Button, { variant: "primary", children: "Save Changes" }) })] }), _jsxs(Card, { variant: "default", padding: "lg", className: "lg:col-span-3", children: [_jsx(CardTitle, { className: "mb-6", children: "Credentials & Certifications" }), _jsx("div", { className: "grid sm:grid-cols-2 lg:grid-cols-4 gap-4", children: [
                                    { name: 'Security Licence', status: 'Verified', marker: 'SL' },
                                    { name: 'First Aid', status: 'Verified', marker: 'FA' },
                                    { name: 'RSA', status: 'Verified', marker: 'RS' },
                                    { name: 'Crowd Control', status: 'Pending', marker: 'CC' },
                                ].map((cert) => (_jsxs("div", { className: "flex items-center gap-3 p-4 rounded-lg bg-grey-100", children: [_jsx("div", { className: `w-10 h-10 rounded-lg flex items-center justify-center ${cert.status === 'Verified' ? 'bg-success/20' : 'bg-warning/20'}`, children: _jsx("span", { className: `text-xs font-bold ${cert.status === 'Verified' ? 'text-success' : 'text-warning'}`, children: cert.marker }) }), _jsxs("div", { children: [_jsx("p", { className: "font-medium text-text-primary", children: cert.name }), _jsx("p", { className: `text-sm ${cert.status === 'Verified' ? 'text-success' : 'text-warning'}`, children: cert.status })] })] }, cert.name))) })] })] })] }));
}
//# sourceMappingURL=ProfilePage.js.map